"""empty message

Revision ID: 9e87e8a61708
Revises: e748b3ccd4b3
Create Date: 2016-04-07 12:38:45.896428

"""

# revision identifiers, used by Alembic.
revision = '9e87e8a61708'
down_revision = 'e748b3ccd4b3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column(
        'comment_markdown', sa.UnicodeText(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'comment_markdown')
    ### end Alembic commands ###
