"""empty message

Revision ID: a1ca6b9c10ec
Revises: None
Create Date: 2016-04-06 21:32:41.045932

"""

# revision identifiers, used by Alembic.
revision = 'a1ca6b9c10ec'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('userid', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=True),
                    sa.Column('email', sa.String(length=255), nullable=True),
                    sa.Column('password', sa.String(
                        length=255), nullable=True),
                    sa.Column('token', sa.String(length=255), nullable=True),
                    sa.Column('valid', sa.Boolean(), nullable=True),
                    sa.Column('google_id', sa.String(
                        length=255), nullable=True),
                    sa.Column('twitter_id', sa.String(
                        length=255), nullable=True),
                    sa.Column('facebook_id', sa.String(
                        length=255), nullable=True),
                    sa.Column('github_id', sa.String(
                        length=255), nullable=True),
                    sa.Column('temporary', sa.String(
                        length=255), nullable=True),
                    sa.Column('icon', sa.String(length=255), nullable=True),
                    sa.Column('icon_id', sa.String(length=255), nullable=True),
                    sa.Column('created', sa.String(length=255), nullable=True),
                    sa.Column('modified', sa.String(
                        length=255), nullable=True),
                    sa.PrimaryKeyConstraint('userid')
                    )
    op.create_table('topics',
                    sa.Column('topicid', sa.Integer(), nullable=False),
                    sa.Column('topic_delete', sa.Boolean(), nullable=True),
                    sa.Column('topicuuid', sa.String(
                        length=255), nullable=True),
                    sa.Column('userid', sa.Integer(), nullable=True),
                    sa.Column('topic', sa.UnicodeText(), nullable=True),
                    sa.Column('image', sa.String(length=255), nullable=True),
                    sa.Column('image_id', sa.String(
                        length=255), nullable=True),
                    sa.Column('created', sa.String(length=255), nullable=True),
                    sa.Column('modified', sa.String(
                        length=255), nullable=True),
                    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ),
                    sa.PrimaryKeyConstraint('topicid')
                    )
    op.create_table('comments',
                    sa.Column('commentid', sa.Integer(), nullable=False),
                    sa.Column('commentuuid', sa.String(
                        length=255), nullable=True),
                    sa.Column('topicid', sa.Integer(), nullable=True),
                    sa.Column('userid', sa.Integer(), nullable=True),
                    sa.Column('comment_delete', sa.Boolean(), nullable=True),
                    sa.Column('comment', sa.UnicodeText(), nullable=True),
                    sa.Column('image', sa.String(length=255), nullable=True),
                    sa.Column('image_id', sa.String(
                        length=255), nullable=True),
                    sa.Column('created', sa.String(length=255), nullable=True),
                    sa.Column('modified', sa.String(
                        length=255), nullable=True),
                    sa.ForeignKeyConstraint(['topicid'], ['topics.topicid'], ),
                    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ),
                    sa.PrimaryKeyConstraint('commentid')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('topics')
    op.drop_table('users')
    ### end Alembic commands ###
