"""empty message

Revision ID: e748b3ccd4b3
Revises: a1ca6b9c10ec
Create Date: 2016-04-07 12:07:51.520088

"""

# revision identifiers, used by Alembic.
revision = 'e748b3ccd4b3'
down_revision = 'a1ca6b9c10ec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column(
        'topic_markdown', sa.UnicodeText(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'topic_markdown')
    ### end Alembic commands ###
